name: Test
on: [push, pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          conda install pip
          pip install --upgrade pip
          pip install -e .
          pip install pytest>=3.8.0 pytest-cov>=2.3.1 pytest-mock
      - name: Run pytest
        run: |
          pytest
      - name: Save coverage report
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: doc/cov
